// TagCallbackInfo.h
#pragma once

#include "UpdatePipeline.h"

namespace sge
{
    struct SystemFrame;

    struct TagCallbackInfo
    {
        //////////////////
        ///   Fields   ///
    public:

        /**
         * \brief The system that this tag callback belongs to.
         * This indicates that this tag callback should not be invoked for tags generated by that system.
         */
        UpdatePipeline::SystemToken system = UpdatePipeline::NO_SYSTEM;

        /**
         * \brief The type of component this callback is supposed to be called for.
         */
        const TypeInfo* component_type = nullptr;

        /**
         * \brief Any special options this tag callback was created with.
         */
        TagCallbackOptions_t options = TCO_NONE;

        /**
         * \brief The tag callback.
         */
        UFunction<UpdatePipeline::TagCallbackFn> callback;
    };
}
